train:
  _target_: src.datasets.CommonVoiceDataset
  split: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.CommonVoiceDataset
  split: "validation"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  # we want to track performance on librispeech also
  _target_: src.datasets.LibrispeechDataset
  part: "dev-other"
  instance_transforms: ${transforms.instance_transforms.inference}
