train:
  _target_: src.datasets.CommonVoiceDataset
  split: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "validation"
  instance_transforms: ${transforms.instance_transforms.inference}