train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-other"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-other"
  instance_transforms: ${transforms.instance_transforms.inference}