defaults:
  - storage: storage

inference:
  # metrics that are calculated during inference
  - ${metrics.storage.cer_argmax}
  - ${metrics.storage.wer_argmax}
  - ${metrics.storage.wer_beam_search_fast_lm_unigram}
