train:
  - _target_: src.metrics.CERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
    text_encoder: 
      _target_: src.text_encoder.TextEncoder
    text_decoder: 
      _target_: src.text_decoder.ArgmaxDecoder
      encoder:
        _target_: src.text_encoder.TextEncoder
  - _target_: src.metrics.WERMetric
    name: "WER_(Argmax)"
    text_encoder: 
      _target_: src.text_encoder.TextEncoder
    text_decoder: 
      _target_: src.text_decoder.ArgmaxDecoder
      encoder:
        _target_: src.text_encoder.TextEncoder

inference:
  # metrics that are calculated during validation
  - _target_: src.metrics.CERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
    text_encoder: 
      _target_: src.text_encoder.TextEncoder
    text_decoder: 
      _target_: src.text_decoder.ArgmaxDecoder
      encoder:
        _target_: src.text_encoder.TextEncoder
  - _target_: src.metrics.WERMetric
    name: "WER_(Argmax)"
    text_encoder: 
      _target_: src.text_encoder.TextEncoder
    text_decoder: 
      _target_: src.text_decoder.ArgmaxDecoder
      encoder:
        _target_: src.text_encoder.TextEncoder
