defaults:
  - storage: storage

train:
  - ${metrics.storage.cer_argmax}
  - ${metrics.storage.wer_argmax}

inference:
  # metrics that are calculated during validation
  - ${metrics.storage.cer_argmax}
  - ${metrics.storage.wer_argmax}
  - ${metrics.storage.wer_beam_search_fast}
  