defaults:
  - model: deepspeech2
  - metrics: metrics
  - datasets: librispeech-clean-test
  - dataloader: dataloader
  - transforms: transforms
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: "cuda"
  save_path: null # any name here, can be a dataset name
  seed: 1
  from_pretrained: null # path to the pretrained model
