instance_transforms:
  n_fft: 300
  sample_rate: 16000

  train:
    get_spectrogram: # special key for getting spectrogram
      _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: ${transforms.instance_transforms.sample_rate}
      n_fft: ${transforms.instance_transforms.n_fft} 
  inference:
    get_spectrogram:
      _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: ${transforms.instance_transforms.sample_rate}
      n_fft: ${transforms.instance_transforms.n_fft} 

# these lines are required if you do not use batch transforms
batch_transforms:
  train: null
  inference: null
