n_fft: 600
normalize:
  _target_: src.transforms.Normalize0d
  mean: -5.457
  std: 4.168

instance_transforms:
  get_spectrogram: # special key for getting spectrogram
    _target_: torch.nn.Sequential
    _args_:
      - _target_: torchaudio.transforms.MelSpectrogram
        sample_rate: 16000
        n_fft: ${transforms.n_fft}
      - _target_: src.transforms.LogStable

  train:
    get_spectrogram: ${transforms.instance_transforms.get_spectrogram}
  inference:
    get_spectrogram: ${transforms.instance_transforms.get_spectrogram}

batch_transforms:
  train:
    spectrogram:
      _target_: torch.nn.Sequential
      _args_:
        - ${transforms.normalize}
        - _target_: torchaudio.transforms.FrequencyMasking
          freq_mask_param: 27
          iid_masks: true
        - _target_: torchaudio.transforms.TimeMasking
          time_mask_param: 72
          iid_masks: true

  inference:
    spectrogram: ${transforms.normalize}
